package com.powerdata.system.domain;

import java.util.ArrayList;
import java.util.List;

public class IcebergSyncTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    public IcebergSyncTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSourcetypesIsNull() {
            addCriterion("sourcetypes is null");
            return (Criteria) this;
        }

        public Criteria andSourcetypesIsNotNull() {
            addCriterion("sourcetypes is not null");
            return (Criteria) this;
        }

        public Criteria andSourcetypesEqualTo(String value) {
            addCriterion("sourcetypes =", value, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourcetypesNotEqualTo(String value) {
            addCriterion("sourcetypes <>", value, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourcetypesGreaterThan(String value) {
            addCriterion("sourcetypes >", value, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourcetypesGreaterThanOrEqualTo(String value) {
            addCriterion("sourcetypes >=", value, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourcetypesLessThan(String value) {
            addCriterion("sourcetypes <", value, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourcetypesLessThanOrEqualTo(String value) {
            addCriterion("sourcetypes <=", value, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourcetypesLike(String value) {
            addCriterion("sourcetypes like", value, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourcetypesNotLike(String value) {
            addCriterion("sourcetypes not like", value, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourcetypesIn(List<String> values) {
            addCriterion("sourcetypes in", values, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourcetypesNotIn(List<String> values) {
            addCriterion("sourcetypes not in", values, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourcetypesBetween(String value1, String value2) {
            addCriterion("sourcetypes between", value1, value2, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourcetypesNotBetween(String value1, String value2) {
            addCriterion("sourcetypes not between", value1, value2, "sourcetypes");
            return (Criteria) this;
        }

        public Criteria andSourceipIsNull() {
            addCriterion("sourceip is null");
            return (Criteria) this;
        }

        public Criteria andSourceipIsNotNull() {
            addCriterion("sourceip is not null");
            return (Criteria) this;
        }

        public Criteria andSourceipEqualTo(String value) {
            addCriterion("sourceip =", value, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSourceipNotEqualTo(String value) {
            addCriterion("sourceip <>", value, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSourceipGreaterThan(String value) {
            addCriterion("sourceip >", value, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSourceipGreaterThanOrEqualTo(String value) {
            addCriterion("sourceip >=", value, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSourceipLessThan(String value) {
            addCriterion("sourceip <", value, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSourceipLessThanOrEqualTo(String value) {
            addCriterion("sourceip <=", value, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSourceipLike(String value) {
            addCriterion("sourceip like", value, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSourceipNotLike(String value) {
            addCriterion("sourceip not like", value, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSourceipIn(List<String> values) {
            addCriterion("sourceip in", values, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSourceipNotIn(List<String> values) {
            addCriterion("sourceip not in", values, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSourceipBetween(String value1, String value2) {
            addCriterion("sourceip between", value1, value2, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSourceipNotBetween(String value1, String value2) {
            addCriterion("sourceip not between", value1, value2, "sourceip");
            return (Criteria) this;
        }

        public Criteria andSyncdataIsNull() {
            addCriterion("syncdata is null");
            return (Criteria) this;
        }

        public Criteria andSyncdataIsNotNull() {
            addCriterion("syncdata is not null");
            return (Criteria) this;
        }

        public Criteria andSyncdataEqualTo(String value) {
            addCriterion("syncdata =", value, "syncdata");
            return (Criteria) this;
        }

        public Criteria andSyncdataNotEqualTo(String value) {
            addCriterion("syncdata <>", value, "syncdata");
            return (Criteria) this;
        }

        public Criteria andSyncdataGreaterThan(String value) {
            addCriterion("syncdata >", value, "syncdata");
            return (Criteria) this;
        }

        public Criteria andSyncdataGreaterThanOrEqualTo(String value) {
            addCriterion("syncdata >=", value, "syncdata");
            return (Criteria) this;
        }

        public Criteria andSyncdataLessThan(String value) {
            addCriterion("syncdata <", value, "syncdata");
            return (Criteria) this;
        }

        public Criteria andSyncdataLessThanOrEqualTo(String value) {
            addCriterion("syncdata <=", value, "syncdata");
            return (Criteria) this;
        }

        public Criteria andSyncdataLike(String value) {
            addCriterion("syncdata like", value, "syncdata");
            return (Criteria) this;
        }

        public Criteria andSyncdataNotLike(String value) {
            addCriterion("syncdata not like", value, "syncdata");
            return (Criteria) this;
        }

        public Criteria andSyncdataIn(List<String> values) {
            addCriterion("syncdata in", values, "syncdata");
            return (Criteria) this;
        }

        public Criteria andSyncdataNotIn(List<String> values) {
            addCriterion("syncdata not in", values, "syncdata");
            return (Criteria) this;
        }

        public Criteria andSyncdataBetween(String value1, String value2) {
            addCriterion("syncdata between", value1, value2, "syncdata");
            return (Criteria) this;
        }

        public Criteria andSyncdataNotBetween(String value1, String value2) {
            addCriterion("syncdata not between", value1, value2, "syncdata");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidIsNull() {
            addCriterion("distcatalogid is null");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidIsNotNull() {
            addCriterion("distcatalogid is not null");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidEqualTo(String value) {
            addCriterion("distcatalogid =", value, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidNotEqualTo(String value) {
            addCriterion("distcatalogid <>", value, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidGreaterThan(String value) {
            addCriterion("distcatalogid >", value, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidGreaterThanOrEqualTo(String value) {
            addCriterion("distcatalogid >=", value, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidLessThan(String value) {
            addCriterion("distcatalogid <", value, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidLessThanOrEqualTo(String value) {
            addCriterion("distcatalogid <=", value, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidLike(String value) {
            addCriterion("distcatalogid like", value, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidNotLike(String value) {
            addCriterion("distcatalogid not like", value, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidIn(List<String> values) {
            addCriterion("distcatalogid in", values, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidNotIn(List<String> values) {
            addCriterion("distcatalogid not in", values, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidBetween(String value1, String value2) {
            addCriterion("distcatalogid between", value1, value2, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistcatalogidNotBetween(String value1, String value2) {
            addCriterion("distcatalogid not between", value1, value2, "distcatalogid");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseIsNull() {
            addCriterion("distdatabase is null");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseIsNotNull() {
            addCriterion("distdatabase is not null");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseEqualTo(String value) {
            addCriterion("distdatabase =", value, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseNotEqualTo(String value) {
            addCriterion("distdatabase <>", value, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseGreaterThan(String value) {
            addCriterion("distdatabase >", value, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseGreaterThanOrEqualTo(String value) {
            addCriterion("distdatabase >=", value, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseLessThan(String value) {
            addCriterion("distdatabase <", value, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseLessThanOrEqualTo(String value) {
            addCriterion("distdatabase <=", value, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseLike(String value) {
            addCriterion("distdatabase like", value, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseNotLike(String value) {
            addCriterion("distdatabase not like", value, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseIn(List<String> values) {
            addCriterion("distdatabase in", values, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseNotIn(List<String> values) {
            addCriterion("distdatabase not in", values, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseBetween(String value1, String value2) {
            addCriterion("distdatabase between", value1, value2, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDistdatabaseNotBetween(String value1, String value2) {
            addCriterion("distdatabase not between", value1, value2, "distdatabase");
            return (Criteria) this;
        }

        public Criteria andDisttableIsNull() {
            addCriterion("disttable is null");
            return (Criteria) this;
        }

        public Criteria andDisttableIsNotNull() {
            addCriterion("disttable is not null");
            return (Criteria) this;
        }

        public Criteria andDisttableEqualTo(String value) {
            addCriterion("disttable =", value, "disttable");
            return (Criteria) this;
        }

        public Criteria andDisttableNotEqualTo(String value) {
            addCriterion("disttable <>", value, "disttable");
            return (Criteria) this;
        }

        public Criteria andDisttableGreaterThan(String value) {
            addCriterion("disttable >", value, "disttable");
            return (Criteria) this;
        }

        public Criteria andDisttableGreaterThanOrEqualTo(String value) {
            addCriterion("disttable >=", value, "disttable");
            return (Criteria) this;
        }

        public Criteria andDisttableLessThan(String value) {
            addCriterion("disttable <", value, "disttable");
            return (Criteria) this;
        }

        public Criteria andDisttableLessThanOrEqualTo(String value) {
            addCriterion("disttable <=", value, "disttable");
            return (Criteria) this;
        }

        public Criteria andDisttableLike(String value) {
            addCriterion("disttable like", value, "disttable");
            return (Criteria) this;
        }

        public Criteria andDisttableNotLike(String value) {
            addCriterion("disttable not like", value, "disttable");
            return (Criteria) this;
        }

        public Criteria andDisttableIn(List<String> values) {
            addCriterion("disttable in", values, "disttable");
            return (Criteria) this;
        }

        public Criteria andDisttableNotIn(List<String> values) {
            addCriterion("disttable not in", values, "disttable");
            return (Criteria) this;
        }

        public Criteria andDisttableBetween(String value1, String value2) {
            addCriterion("disttable between", value1, value2, "disttable");
            return (Criteria) this;
        }

        public Criteria andDisttableNotBetween(String value1, String value2) {
            addCriterion("disttable not between", value1, value2, "disttable");
            return (Criteria) this;
        }

        public Criteria andExectimesIsNull() {
            addCriterion("exectimes is null");
            return (Criteria) this;
        }

        public Criteria andExectimesIsNotNull() {
            addCriterion("exectimes is not null");
            return (Criteria) this;
        }

        public Criteria andExectimesEqualTo(String value) {
            addCriterion("exectimes =", value, "exectimes");
            return (Criteria) this;
        }

        public Criteria andExectimesNotEqualTo(String value) {
            addCriterion("exectimes <>", value, "exectimes");
            return (Criteria) this;
        }

        public Criteria andExectimesGreaterThan(String value) {
            addCriterion("exectimes >", value, "exectimes");
            return (Criteria) this;
        }

        public Criteria andExectimesGreaterThanOrEqualTo(String value) {
            addCriterion("exectimes >=", value, "exectimes");
            return (Criteria) this;
        }

        public Criteria andExectimesLessThan(String value) {
            addCriterion("exectimes <", value, "exectimes");
            return (Criteria) this;
        }

        public Criteria andExectimesLessThanOrEqualTo(String value) {
            addCriterion("exectimes <=", value, "exectimes");
            return (Criteria) this;
        }

        public Criteria andExectimesLike(String value) {
            addCriterion("exectimes like", value, "exectimes");
            return (Criteria) this;
        }

        public Criteria andExectimesNotLike(String value) {
            addCriterion("exectimes not like", value, "exectimes");
            return (Criteria) this;
        }

        public Criteria andExectimesIn(List<String> values) {
            addCriterion("exectimes in", values, "exectimes");
            return (Criteria) this;
        }

        public Criteria andExectimesNotIn(List<String> values) {
            addCriterion("exectimes not in", values, "exectimes");
            return (Criteria) this;
        }

        public Criteria andExectimesBetween(String value1, String value2) {
            addCriterion("exectimes between", value1, value2, "exectimes");
            return (Criteria) this;
        }

        public Criteria andExectimesNotBetween(String value1, String value2) {
            addCriterion("exectimes not between", value1, value2, "exectimes");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createtime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createtime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther2IsNull() {
            addCriterion("other2 is null");
            return (Criteria) this;
        }

        public Criteria andOther2IsNotNull() {
            addCriterion("other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOther2EqualTo(String value) {
            addCriterion("other2 =", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotEqualTo(String value) {
            addCriterion("other2 <>", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThan(String value) {
            addCriterion("other2 >", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThanOrEqualTo(String value) {
            addCriterion("other2 >=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThan(String value) {
            addCriterion("other2 <", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThanOrEqualTo(String value) {
            addCriterion("other2 <=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Like(String value) {
            addCriterion("other2 like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotLike(String value) {
            addCriterion("other2 not like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2In(List<String> values) {
            addCriterion("other2 in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotIn(List<String> values) {
            addCriterion("other2 not in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Between(String value1, String value2) {
            addCriterion("other2 between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotBetween(String value1, String value2) {
            addCriterion("other2 not between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther3IsNull() {
            addCriterion("other3 is null");
            return (Criteria) this;
        }

        public Criteria andOther3IsNotNull() {
            addCriterion("other3 is not null");
            return (Criteria) this;
        }

        public Criteria andOther3EqualTo(String value) {
            addCriterion("other3 =", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3NotEqualTo(String value) {
            addCriterion("other3 <>", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3GreaterThan(String value) {
            addCriterion("other3 >", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3GreaterThanOrEqualTo(String value) {
            addCriterion("other3 >=", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3LessThan(String value) {
            addCriterion("other3 <", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3LessThanOrEqualTo(String value) {
            addCriterion("other3 <=", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3Like(String value) {
            addCriterion("other3 like", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3NotLike(String value) {
            addCriterion("other3 not like", value, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3In(List<String> values) {
            addCriterion("other3 in", values, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3NotIn(List<String> values) {
            addCriterion("other3 not in", values, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3Between(String value1, String value2) {
            addCriterion("other3 between", value1, value2, "other3");
            return (Criteria) this;
        }

        public Criteria andOther3NotBetween(String value1, String value2) {
            addCriterion("other3 not between", value1, value2, "other3");
            return (Criteria) this;
        }

        public Criteria andOther4IsNull() {
            addCriterion("other4 is null");
            return (Criteria) this;
        }

        public Criteria andOther4IsNotNull() {
            addCriterion("other4 is not null");
            return (Criteria) this;
        }

        public Criteria andOther4EqualTo(String value) {
            addCriterion("other4 =", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4NotEqualTo(String value) {
            addCriterion("other4 <>", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4GreaterThan(String value) {
            addCriterion("other4 >", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4GreaterThanOrEqualTo(String value) {
            addCriterion("other4 >=", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4LessThan(String value) {
            addCriterion("other4 <", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4LessThanOrEqualTo(String value) {
            addCriterion("other4 <=", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4Like(String value) {
            addCriterion("other4 like", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4NotLike(String value) {
            addCriterion("other4 not like", value, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4In(List<String> values) {
            addCriterion("other4 in", values, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4NotIn(List<String> values) {
            addCriterion("other4 not in", values, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4Between(String value1, String value2) {
            addCriterion("other4 between", value1, value2, "other4");
            return (Criteria) this;
        }

        public Criteria andOther4NotBetween(String value1, String value2) {
            addCriterion("other4 not between", value1, value2, "other4");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 29 16:07:24 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}