package com.powerdata.system.domain;

public class IcebergCatalog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_catalog.id
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    private String id;//catalogId

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_catalog.descs
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_catalog.types
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    private String types;//hive or hadoop

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_catalog.hiveUrl
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    private String hiveurl;//types = hive

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_catalog.hdfsUrl
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    private String hdfsurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_catalog.creataBy
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    private String creataby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_catalog.createTime
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_catalog.modifyBy
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    private String modifyby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_catalog.modifyTime
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    private String modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_catalog.id
     *
     * @return the value of iceberg_catalog.id
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_catalog.id
     *
     * @param id the value for iceberg_catalog.id
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_catalog.descs
     *
     * @return the value of iceberg_catalog.descs
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_catalog.descs
     *
     * @param descs the value for iceberg_catalog.descs
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_catalog.types
     *
     * @return the value of iceberg_catalog.types
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_catalog.types
     *
     * @param types the value for iceberg_catalog.types
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_catalog.hiveUrl
     *
     * @return the value of iceberg_catalog.hiveUrl
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public String getHiveurl() {
        return hiveurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_catalog.hiveUrl
     *
     * @param hiveurl the value for iceberg_catalog.hiveUrl
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void setHiveurl(String hiveurl) {
        this.hiveurl = hiveurl == null ? null : hiveurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_catalog.hdfsUrl
     *
     * @return the value of iceberg_catalog.hdfsUrl
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public String getHdfsurl() {
        return hdfsurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_catalog.hdfsUrl
     *
     * @param hdfsurl the value for iceberg_catalog.hdfsUrl
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void setHdfsurl(String hdfsurl) {
        this.hdfsurl = hdfsurl == null ? null : hdfsurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_catalog.creataBy
     *
     * @return the value of iceberg_catalog.creataBy
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public String getCreataby() {
        return creataby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_catalog.creataBy
     *
     * @param creataby the value for iceberg_catalog.creataBy
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void setCreataby(String creataby) {
        this.creataby = creataby == null ? null : creataby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_catalog.createTime
     *
     * @return the value of iceberg_catalog.createTime
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_catalog.createTime
     *
     * @param createtime the value for iceberg_catalog.createTime
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_catalog.modifyBy
     *
     * @return the value of iceberg_catalog.modifyBy
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public String getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_catalog.modifyBy
     *
     * @param modifyby the value for iceberg_catalog.modifyBy
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void setModifyby(String modifyby) {
        this.modifyby = modifyby == null ? null : modifyby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_catalog.modifyTime
     *
     * @return the value of iceberg_catalog.modifyTime
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_catalog.modifyTime
     *
     * @param modifytime the value for iceberg_catalog.modifyTime
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime == null ? null : modifytime.trim();
    }
}