package com.powerdata.system.domain;

import java.util.ArrayList;
import java.util.List;

public class IcebergCatalogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public IcebergCatalogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDescsIsNull() {
            addCriterion("descs is null");
            return (Criteria) this;
        }

        public Criteria andDescsIsNotNull() {
            addCriterion("descs is not null");
            return (Criteria) this;
        }

        public Criteria andDescsEqualTo(String value) {
            addCriterion("descs =", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotEqualTo(String value) {
            addCriterion("descs <>", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsGreaterThan(String value) {
            addCriterion("descs >", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsGreaterThanOrEqualTo(String value) {
            addCriterion("descs >=", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsLessThan(String value) {
            addCriterion("descs <", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsLessThanOrEqualTo(String value) {
            addCriterion("descs <=", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsLike(String value) {
            addCriterion("descs like", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotLike(String value) {
            addCriterion("descs not like", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsIn(List<String> values) {
            addCriterion("descs in", values, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotIn(List<String> values) {
            addCriterion("descs not in", values, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsBetween(String value1, String value2) {
            addCriterion("descs between", value1, value2, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotBetween(String value1, String value2) {
            addCriterion("descs not between", value1, value2, "descs");
            return (Criteria) this;
        }

        public Criteria andTypesIsNull() {
            addCriterion("types is null");
            return (Criteria) this;
        }

        public Criteria andTypesIsNotNull() {
            addCriterion("types is not null");
            return (Criteria) this;
        }

        public Criteria andTypesEqualTo(String value) {
            addCriterion("types =", value, "types");
            return (Criteria) this;
        }

        public Criteria andTypesNotEqualTo(String value) {
            addCriterion("types <>", value, "types");
            return (Criteria) this;
        }

        public Criteria andTypesGreaterThan(String value) {
            addCriterion("types >", value, "types");
            return (Criteria) this;
        }

        public Criteria andTypesGreaterThanOrEqualTo(String value) {
            addCriterion("types >=", value, "types");
            return (Criteria) this;
        }

        public Criteria andTypesLessThan(String value) {
            addCriterion("types <", value, "types");
            return (Criteria) this;
        }

        public Criteria andTypesLessThanOrEqualTo(String value) {
            addCriterion("types <=", value, "types");
            return (Criteria) this;
        }

        public Criteria andTypesLike(String value) {
            addCriterion("types like", value, "types");
            return (Criteria) this;
        }

        public Criteria andTypesNotLike(String value) {
            addCriterion("types not like", value, "types");
            return (Criteria) this;
        }

        public Criteria andTypesIn(List<String> values) {
            addCriterion("types in", values, "types");
            return (Criteria) this;
        }

        public Criteria andTypesNotIn(List<String> values) {
            addCriterion("types not in", values, "types");
            return (Criteria) this;
        }

        public Criteria andTypesBetween(String value1, String value2) {
            addCriterion("types between", value1, value2, "types");
            return (Criteria) this;
        }

        public Criteria andTypesNotBetween(String value1, String value2) {
            addCriterion("types not between", value1, value2, "types");
            return (Criteria) this;
        }

        public Criteria andHiveurlIsNull() {
            addCriterion("hiveUrl is null");
            return (Criteria) this;
        }

        public Criteria andHiveurlIsNotNull() {
            addCriterion("hiveUrl is not null");
            return (Criteria) this;
        }

        public Criteria andHiveurlEqualTo(String value) {
            addCriterion("hiveUrl =", value, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHiveurlNotEqualTo(String value) {
            addCriterion("hiveUrl <>", value, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHiveurlGreaterThan(String value) {
            addCriterion("hiveUrl >", value, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHiveurlGreaterThanOrEqualTo(String value) {
            addCriterion("hiveUrl >=", value, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHiveurlLessThan(String value) {
            addCriterion("hiveUrl <", value, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHiveurlLessThanOrEqualTo(String value) {
            addCriterion("hiveUrl <=", value, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHiveurlLike(String value) {
            addCriterion("hiveUrl like", value, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHiveurlNotLike(String value) {
            addCriterion("hiveUrl not like", value, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHiveurlIn(List<String> values) {
            addCriterion("hiveUrl in", values, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHiveurlNotIn(List<String> values) {
            addCriterion("hiveUrl not in", values, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHiveurlBetween(String value1, String value2) {
            addCriterion("hiveUrl between", value1, value2, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHiveurlNotBetween(String value1, String value2) {
            addCriterion("hiveUrl not between", value1, value2, "hiveurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlIsNull() {
            addCriterion("hdfsUrl is null");
            return (Criteria) this;
        }

        public Criteria andHdfsurlIsNotNull() {
            addCriterion("hdfsUrl is not null");
            return (Criteria) this;
        }

        public Criteria andHdfsurlEqualTo(String value) {
            addCriterion("hdfsUrl =", value, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlNotEqualTo(String value) {
            addCriterion("hdfsUrl <>", value, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlGreaterThan(String value) {
            addCriterion("hdfsUrl >", value, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlGreaterThanOrEqualTo(String value) {
            addCriterion("hdfsUrl >=", value, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlLessThan(String value) {
            addCriterion("hdfsUrl <", value, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlLessThanOrEqualTo(String value) {
            addCriterion("hdfsUrl <=", value, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlLike(String value) {
            addCriterion("hdfsUrl like", value, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlNotLike(String value) {
            addCriterion("hdfsUrl not like", value, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlIn(List<String> values) {
            addCriterion("hdfsUrl in", values, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlNotIn(List<String> values) {
            addCriterion("hdfsUrl not in", values, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlBetween(String value1, String value2) {
            addCriterion("hdfsUrl between", value1, value2, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andHdfsurlNotBetween(String value1, String value2) {
            addCriterion("hdfsUrl not between", value1, value2, "hdfsurl");
            return (Criteria) this;
        }

        public Criteria andCreatabyIsNull() {
            addCriterion("creataBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatabyIsNotNull() {
            addCriterion("creataBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatabyEqualTo(String value) {
            addCriterion("creataBy =", value, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatabyNotEqualTo(String value) {
            addCriterion("creataBy <>", value, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatabyGreaterThan(String value) {
            addCriterion("creataBy >", value, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatabyGreaterThanOrEqualTo(String value) {
            addCriterion("creataBy >=", value, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatabyLessThan(String value) {
            addCriterion("creataBy <", value, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatabyLessThanOrEqualTo(String value) {
            addCriterion("creataBy <=", value, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatabyLike(String value) {
            addCriterion("creataBy like", value, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatabyNotLike(String value) {
            addCriterion("creataBy not like", value, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatabyIn(List<String> values) {
            addCriterion("creataBy in", values, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatabyNotIn(List<String> values) {
            addCriterion("creataBy not in", values, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatabyBetween(String value1, String value2) {
            addCriterion("creataBy between", value1, value2, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatabyNotBetween(String value1, String value2) {
            addCriterion("creataBy not between", value1, value2, "creataby");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createTime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createTime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andModifybyIsNull() {
            addCriterion("modifyBy is null");
            return (Criteria) this;
        }

        public Criteria andModifybyIsNotNull() {
            addCriterion("modifyBy is not null");
            return (Criteria) this;
        }

        public Criteria andModifybyEqualTo(String value) {
            addCriterion("modifyBy =", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotEqualTo(String value) {
            addCriterion("modifyBy <>", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyGreaterThan(String value) {
            addCriterion("modifyBy >", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyGreaterThanOrEqualTo(String value) {
            addCriterion("modifyBy >=", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLessThan(String value) {
            addCriterion("modifyBy <", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLessThanOrEqualTo(String value) {
            addCriterion("modifyBy <=", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLike(String value) {
            addCriterion("modifyBy like", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotLike(String value) {
            addCriterion("modifyBy not like", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyIn(List<String> values) {
            addCriterion("modifyBy in", values, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotIn(List<String> values) {
            addCriterion("modifyBy not in", values, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyBetween(String value1, String value2) {
            addCriterion("modifyBy between", value1, value2, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotBetween(String value1, String value2) {
            addCriterion("modifyBy not between", value1, value2, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNull() {
            addCriterion("modifyTime is null");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNotNull() {
            addCriterion("modifyTime is not null");
            return (Criteria) this;
        }

        public Criteria andModifytimeEqualTo(String value) {
            addCriterion("modifyTime =", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotEqualTo(String value) {
            addCriterion("modifyTime <>", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThan(String value) {
            addCriterion("modifyTime >", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThanOrEqualTo(String value) {
            addCriterion("modifyTime >=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThan(String value) {
            addCriterion("modifyTime <", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThanOrEqualTo(String value) {
            addCriterion("modifyTime <=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLike(String value) {
            addCriterion("modifyTime like", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotLike(String value) {
            addCriterion("modifyTime not like", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeIn(List<String> values) {
            addCriterion("modifyTime in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotIn(List<String> values) {
            addCriterion("modifyTime not in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeBetween(String value1, String value2) {
            addCriterion("modifyTime between", value1, value2, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotBetween(String value1, String value2) {
            addCriterion("modifyTime not between", value1, value2, "modifytime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iceberg_catalog
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 12 13:40:10 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}