package com.powerdata.system.domain;

public class IcebergExecLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_exec_log.id
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_exec_log.sqlstr
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    private String sqlstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_exec_log.status
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_exec_log.createtime
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_exec_log.exectimes
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    private String exectimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_exec_log.creater
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_exec_log.other1
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_exec_log.other2
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    private String other2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_exec_log.id
     *
     * @return the value of iceberg_exec_log.id
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_exec_log.id
     *
     * @param id the value for iceberg_exec_log.id
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_exec_log.sqlstr
     *
     * @return the value of iceberg_exec_log.sqlstr
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public String getSqlstr() {
        return sqlstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_exec_log.sqlstr
     *
     * @param sqlstr the value for iceberg_exec_log.sqlstr
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public void setSqlstr(String sqlstr) {
        this.sqlstr = sqlstr == null ? null : sqlstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_exec_log.status
     *
     * @return the value of iceberg_exec_log.status
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_exec_log.status
     *
     * @param status the value for iceberg_exec_log.status
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_exec_log.createtime
     *
     * @return the value of iceberg_exec_log.createtime
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_exec_log.createtime
     *
     * @param createtime the value for iceberg_exec_log.createtime
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_exec_log.exectimes
     *
     * @return the value of iceberg_exec_log.exectimes
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public String getExectimes() {
        return exectimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_exec_log.exectimes
     *
     * @param exectimes the value for iceberg_exec_log.exectimes
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public void setExectimes(String exectimes) {
        this.exectimes = exectimes == null ? null : exectimes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_exec_log.creater
     *
     * @return the value of iceberg_exec_log.creater
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_exec_log.creater
     *
     * @param creater the value for iceberg_exec_log.creater
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_exec_log.other1
     *
     * @return the value of iceberg_exec_log.other1
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_exec_log.other1
     *
     * @param other1 the value for iceberg_exec_log.other1
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_exec_log.other2
     *
     * @return the value of iceberg_exec_log.other2
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_exec_log.other2
     *
     * @param other2 the value for iceberg_exec_log.other2
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }
}