package com.powerdata.system.domain;

public class IcebergSaveSql {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_save_sql.name
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_save_sql.execsql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    private String execsql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_save_sql.creater
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iceberg_save_sql.createtime
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_save_sql.name
     *
     * @return the value of iceberg_save_sql.name
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_save_sql.name
     *
     * @param name the value for iceberg_save_sql.name
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_save_sql.execsql
     *
     * @return the value of iceberg_save_sql.execsql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    public String getExecsql() {
        return execsql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_save_sql.execsql
     *
     * @param execsql the value for iceberg_save_sql.execsql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    public void setExecsql(String execsql) {
        this.execsql = execsql == null ? null : execsql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_save_sql.creater
     *
     * @return the value of iceberg_save_sql.creater
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_save_sql.creater
     *
     * @param creater the value for iceberg_save_sql.creater
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iceberg_save_sql.createtime
     *
     * @return the value of iceberg_save_sql.createtime
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iceberg_save_sql.createtime
     *
     * @param createtime the value for iceberg_save_sql.createtime
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }
}