package com.powerdata.system.mapper;

import com.powerdata.system.domain.IcebergSaveSql;
import com.powerdata.system.domain.IcebergSaveSqlExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IcebergSaveSqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_save_sql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    int countByExample(IcebergSaveSqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_save_sql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    int deleteByExample(IcebergSaveSqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_save_sql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_save_sql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    int insert(IcebergSaveSql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_save_sql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    int insertSelective(IcebergSaveSql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_save_sql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    List<IcebergSaveSql> selectByExample(IcebergSaveSqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_save_sql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    IcebergSaveSql selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_save_sql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    int updateByExampleSelective(@Param("record") IcebergSaveSql record, @Param("example") IcebergSaveSqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_save_sql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    int updateByExample(@Param("record") IcebergSaveSql record, @Param("example") IcebergSaveSqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_save_sql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    int updateByPrimaryKeySelective(IcebergSaveSql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_save_sql
     *
     * @mbggenerated Thu Aug 24 16:07:45 CST 2023
     */
    int updateByPrimaryKey(IcebergSaveSql record);
}