package com.powerdata.system.mapper;

import com.powerdata.system.domain.IcebergSyncTask;
import com.powerdata.system.domain.IcebergSyncTaskExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IcebergSyncTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    int countByExample(IcebergSyncTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    int deleteByExample(IcebergSyncTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    int insert(IcebergSyncTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    int insertSelective(IcebergSyncTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    List<IcebergSyncTask> selectByExample(IcebergSyncTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    IcebergSyncTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    int updateByExampleSelective(@Param("record") IcebergSyncTask record, @Param("example") IcebergSyncTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    int updateByExample(@Param("record") IcebergSyncTask record, @Param("example") IcebergSyncTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    int updateByPrimaryKeySelective(IcebergSyncTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_sync_task
     *
     * @mbggenerated Tue Aug 29 16:07:24 CST 2023
     */
    int updateByPrimaryKey(IcebergSyncTask record);
}