package com.powerdata.system.mapper;

import com.powerdata.system.domain.IcebergCatalog;
import com.powerdata.system.domain.IcebergCatalogExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IcebergCatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    int countByExample(IcebergCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    int deleteByExample(IcebergCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    int insert(IcebergCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    int insertSelective(IcebergCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    List<IcebergCatalog> selectByExample(IcebergCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    IcebergCatalog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    int updateByExampleSelective(@Param("record") IcebergCatalog record, @Param("example") IcebergCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    int updateByExample(@Param("record") IcebergCatalog record, @Param("example") IcebergCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    int updateByPrimaryKeySelective(IcebergCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_catalog
     *
     * @mbggenerated Mon Jun 12 13:40:10 CST 2023
     */
    int updateByPrimaryKey(IcebergCatalog record);
}