package com.powerdata.system.mapper;

import com.powerdata.system.domain.IcebergExecLog;
import com.powerdata.system.domain.IcebergExecLogExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IcebergExecLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_exec_log
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    int countByExample(IcebergExecLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_exec_log
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    int deleteByExample(IcebergExecLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_exec_log
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_exec_log
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    int insert(IcebergExecLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_exec_log
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    int insertSelective(IcebergExecLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_exec_log
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    List<IcebergExecLog> selectByExample(IcebergExecLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_exec_log
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    IcebergExecLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_exec_log
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    int updateByExampleSelective(@Param("record") IcebergExecLog record, @Param("example") IcebergExecLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_exec_log
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    int updateByExample(@Param("record") IcebergExecLog record, @Param("example") IcebergExecLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_exec_log
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    int updateByPrimaryKeySelective(IcebergExecLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iceberg_exec_log
     *
     * @mbggenerated Thu Aug 24 16:57:47 CST 2023
     */
    int updateByPrimaryKey(IcebergExecLog record);
}